---
authors:
  - "René Moser <mail@renemoser.net>"
  - "David Passante (@dpassante)"
  - "Netservers Ltd. <support@netservers.co.uk>"
  - "Patryk D. Cichy <patryk.d.cichy@gmail.com>"
  - "Darren Worrall <darren@iweb.co.uk>"
  - "Marc-Aurèle Brothier (@marcaurele)"
  - "Jefferson Girão <jefferson@girao.net>"
  - "Gregor Riepl (@onitake)"
  - "Rafael del Valle (@rvalle)"
dependencies: {}
description: 'Ansible Collection for Apache CloudStack based clouds'
documentation: ''
homepage: 'https://github.com/ngine-io/ansible-collection-cloudstack'
issues: 'https://github.com/ngine-io/ansible-collection-cloudstack/issues'
license: GPL-3.0-or-later
name: cloudstack
namespace: ngine_io
readme: README.md
repository: 'https://github.com/ngine-io/ansible-collection-cloudstack'
tags:
  - cloud
  - cloudstack
  - ngine_io
version: 2.0.0
